##### **Flask and Web Development**

`Flask` Is a Micro Framework Built with Python, to Make a Good Website You Need to Learn the Following:

↪ HTML

↪ CSS

↪ JavaScript

To Install Flask Use This Command: 

In [ ]:
pip install flask

In [ ]:
from flask import Flask

skills_app = Flask(__name__) # Giving a Name to Our Web App


# Settign up Routes (Homepage, About, Contact, ... Etc.)
@skills_app.route("/")  # Main Route Like elzero.or/

def homepage(): 

    return "Hello From Flask Framework"

def about(): 

    return "Hello From About Page"



if __name__ == "__main__": 

    skills_app.run()


You Can't Run This From Jupyter Notebook for some Reason but You Can in a `.py` File, The Output Wil Lbe Like This: 

In [ ]:
from flask import Flask

skills_app = Flask(__name__) # Giving a Name to Our Web App


# Settign up Routes (Homepage, About, Contact, ... Etc.)
@skills_app.route("/")  # Main Route Like elzero.or/

def homepage(): 

    return "Hello From Flask Framework"

def about(): 

    return "Hello From About Page"



if __name__ == "__main__": 

    skills_app.run()


Now if You Clicked on That `http` Link (The Host) It Will Take You to Your App and You Will See the Homepage, Now Let's Run the Debug and Change the Port

In [ ]:
from flask import Flask

skills_app = Flask(__name__) # Giving a Name to Our Web App


# Settign up Routes (Homepage, About, Contact, ... Etc.)
@skills_app.route("/")  # Main Route Like elzero.or/

def homepage(): 

    return "Hello From Flask Framework"

def about(): 

    return "Hello From About Page"



if __name__ == "__main__": 

    skills_app.run(debug=True, port=7000)


:: `Note` :: pressing <kbd>Ctrl</kbd>+<kbd>C</kbd>  Will Terminate the Current Used Port so You Can Make Changes and Run the App Again.

❖ You Will Also Notice the Response Status Code: `GET / HTTP/1.1" 200` Which Indicate a Successful Resopnse, You Can Know More About This From the Following Link: 

> https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

Now Let's Create the Html Files, and for that we will use the `render_template`

In [ ]:
from flask import Flask, render_template

skills_app = Flask(__name__) # Giving a Name to Our Web App


# Settign up Routes (Homepage, About, Contact, ... Etc.)
@skills_app.route("/")  # Main Route Like elzero.or/

def homepage(): 

    return render_template("/Users/Ahmed/Desktop/Flask_Files/homepage.html")  # Give The Full Path

def about(): 

    return render_template("/Users/Ahmed/Desktop/Flask_Files/about.html")



if __name__ == "__main__": 

    skills_app.run(debug=True, port=7000)


Now in the Html Files You Can Press <kbd>!</kbd> + <kbd>Tab ⇥</kbd> To Create The HTML5 Template Automatically

:: `Note` :: we will make all pages controlled by our `.py` file, So We Can Focus on the Body Part in the Pages, Let's Set the Page Title From Our Python File. 

In [ ]:
from flask import Flask, render_template

skills_app = Flask(__name__) # Giving a Name to Our Web App
skills_app = Flask(__name__, template_folder='/Users/Ahmed/Desktop/Flask_Files') # Setting the Template Folder Where You App Files 


# Settign up routing (Homepage, About, Contact, ... Etc.)
@skills_app.route("/")  # Main Route Like elzero.or/
def homepage(): 

    return render_template("homepage.html", pagetitle="Homepage")

@skills_app.route("/about")
def about(): # about Route Like elzero.or/about

    return render_template("about.html", pagetitle="About")



if __name__ == "__main__": 

    skills_app.run(debug=True, port=7000)


Now We Go to Our Html Files and Make the Title Like This: 

In [ ]:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ pagetitle }}</title>
</head>
<body>
    
</body>
</html>

##### **Extend HTML Templates**

Let's Say Your Web App Has a Lot of Pages and We Need to Change the Css File From main.css File to master.css File, so Instead of Changing This in All the Pages in Our App We Will only Change This Once in the Main Base File and the All the Pages in Our App Will Follow that Main Base File. 

❖ Create a File in Your Template Folder and Neme It `base.html` And Create a Folder Names "`css`" In Our Template Folder and Create `main.css` File Inside It, Here's the Content of of Our `base.html` File

In [ ]:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ pagetitle }}</title>
    <link rel="stylesheet" href="css/main.css"/>
</head>
<body>
    {% block body %} 
    {% endblock %}
</body>
</html>

Now in the Homepage, About, and Every Other Page We Will Deal with the Block Body only so We Will Delete Everything and Just Paste These Lines

In [ ]:
{% extends 'base.html' %}
{% block body %} 

<!-- Our Dynamic Work Will Be Here -->

{% endblock %}

Now We Can Add Another `Css` File to the Base Html File and All Other Pages Will Extend the Css File From the Base Html File

:: `Note` :: these lines we added are from `Jinja` A Modern and Designer-Friendly Templating Language for Python, Modelled After Django's Template, It's Fast, Widely Used and Secure.

❖ There's a vs-Code Extentions for Jinja that Helps with the Syntax Highlighting It's Called `Jina` You Should Install It. 

⟶ Now We Need to Make a `Custom Css File for Everypage` (the Homepage, About Page, ...Etc.) and Create a Contact Route with No Custom Css File for It

↪ By Default `Jinja` Is Looking for Static Folder Which Contains the Css Files in It so We Will Create `css` Folder Inside `static` Folder

In [ ]:
from flask import Flask, render_template

skills_app = Flask(__name__) # Giving a Name to Our Web App
skills_app = Flask(__name__, template_folder='/Users/Ahmed/Desktop/Flask_Files') # Setting the Template Folder Where You App Files 


# Settign up routing (Homepage, About, Contact, ... Etc.)
@skills_app.route("/")  # Main Route Like elzero.or/
def homepage(): 

    return render_template("homepage.html", pagetitle="Homepage", custom_css="home")

@skills_app.route("/about")
def about(): # about Route Like elzero.or/about

    return render_template("about.html", pagetitle="About", custom_css="about")

@skills_app.route("/contact")
def contact(): # about Route Like elzero.or/contact

    return render_template("contact.html", pagetitle="Contact")


if __name__ == "__main__": 

    skills_app.run(debug=True, port=7000)


`Don't Forget` to add `home.css` and `about.css` now in css folder we created

Now We Need to Make `if Condition` in Our base.html that if This Page Has Custom_css Attribute, It Should Add the Corresponding custom.css File to that Page. 

How Can We Achive This? We Will Use `Jinja Syntax` in Our Base File And `Concatenation` in our `base.html` File 

In [ ]:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ pagetitle }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename= 'css/main.css') }}"/>
    
    {% if custom_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/' + custom_css + '.css') }}"/>
    {% endif %}


</head>
<body>
    {% block body %} 
    {% endblock %}
</body>
</html>

You Can Now Check Every Page in the Developer View in Your Browser (Inspect Elements) and in the Sources You'll See that It Reads the `main.css` File and the It's Own File

![Custom Css File](https://i.imgur.com/iteK14J.png)

And You Can Also Check the Console for Any Errors

:: `Skills Page Using List Data` ::

In [ ]:
from flask import Flask, render_template

skills_app = Flask(__name__) # Giving a Name to Our Web App
skills_app = Flask(__name__, template_folder='/Users/Ahmed/Desktop/Flask_Files') # Setting the Template Folder Where You App Files 

# Skills List
my_skills = [("HTML", 80), ("CSS", 75), ("Python", 95)]


# Settign up routing (Homepage, About, Contact, ... Etc.)
@skills_app.route("/")  # Main Route Like elzero.or/
def homepage(): 

    return render_template("homepage.html", pagetitle="Homepage", custom_css="home")

@skills_app.route("/about")
def about(): # about Route Like elzero.or/about

    return render_template("about.html", pagetitle="About", custom_css="about")

@skills_app.route("/skills")
def skills(): # about Route Like elzero.or/contact

    return render_template("skills.html", pagetitle="My Skills", custom_css="skills")




if __name__ == "__main__": 

    skills_app.run(debug=True, port=7000)


❖ Don't Forget to Add the Corresponding Html and Css Files in Their Respective Directories. 

❖ Now Let's Add Page Head and Description

↪ In the Python File We Will Do the Following: 

In [ ]:
from flask import Flask, render_template

skills_app = Flask(__name__) # Giving a Name to Our Web App
skills_app = Flask(__name__, template_folder='/Users/Ahmed/Desktop/Flask_Files') # Setting the Template Folder Where You App Files 

# Skills List
my_skills = [("HTML", 80), ("CSS", 75), ("Python", 95)]


# Settign up routing (Homepage, About, Contact, ... Etc.)
@skills_app.route("/")  # Main Route Like elzero.or/
def homepage(): 

    return render_template("homepage.html", pagetitle="Homepage", custom_css="home")

@skills_app.route("/about")
def about(): # about Route Like elzero.or/about

    return render_template("about.html", pagetitle="About", custom_css="about")

@skills_app.route("/skills")
def skills():

    return render_template("skills.html", pagetitle="My Skills", custom_css="skills", 
                           page_head="My Skills", description="This is my Skills Page")




if __name__ == "__main__": 

    skills_app.run(debug=True, port=7000)


↪ In the skills.html File We Will Do the Following: 

In [ ]:
{% extends 'base.html' %}
{% block body %} 

<h1 class="page-head"> {{ page_head }} </h1>

<p class="page-description"> {{ description }} </p>

{% endblock %}

Now We Should See Something Like This when We Refresh the Page

![skills_app_basic](https://i.imgur.com/mfuxc0F.png)

❖ Now Let's Put the Skills List We Created

↪ In the Python File We Will Do the Following: 

In [ ]:
from flask import Flask, render_template

skills_app = Flask(__name__) # Giving a Name to Our Web App
skills_app = Flask(__name__, template_folder='/Users/Ahmed/Desktop/Flask_Files') # Setting the Template Folder Where You App Files 

# Skills List
my_skills = [("HTML", 80), ("CSS", 75), ("Python", 95)]


# Settign up routing (Homepage, About, Contact, ... Etc.)
@skills_app.route("/")  # Main Route Like elzero.or/
def homepage(): 

    return render_template("homepage.html", pagetitle="Homepage", custom_css="home")

@skills_app.route("/about")
def about(): # about Route Like elzero.or/about

    return render_template("about.html", pagetitle="About", custom_css="about")

@skills_app.route("/skills")
def skills():

    return render_template("skills.html", pagetitle="My Skills", custom_css="skills", 
                           page_head="My Skills", description="This is my Skills Page", 
                           skills=my_skills)




if __name__ == "__main__": 

    skills_app.run(debug=True, port=7000)


↪ In the skills.html File We Will Do the Following: 

In [ ]:
{% extends 'base.html' %}
{% block body %} 

<h1 class="page-head"> {{ page_head }} </h1>

<p class="page-description"> {{ description }} </p>

{{ skills }}

{% endblock %}

We Will See the Skills Printed Like This: 

![skills_printed](https://i.imgur.com/hNFepam.png)

Now We Need to Loop on Those Skills and Let's Say Separate Them Usin a Pipe `|`

↪ Do the Following in the skills.html File

In [ ]:
{% extends 'base.html' %}
{% block body %} 

<h1 class="page-head"> {{ page_head }} </h1>

<p class="page-description"> {{ description }} </p>

{ % for skill in skills % }

<div>
    {{ skill[0] }} | {{ skill[1] }}
</div>

{% endfor %}

{% endblock %}

Now We Should See Something Like This: 

![skills_pip](https://i.imgur.com/XbgLIPt.png)

Now We Will Edit the Rest of the Page Using Css. 

`Customizing App with Css`

❖ Now We Will Hob Into the main.css File to Do the Generic Edits

:: `Note` :: The `<style>` Tag in the Code Is Just for Jupyter for the Purpose of Syntax Highlighting

In [ ]:
<style>
* {
    box-sizing: border-box
}

This CSS Command Tells the Browser to Include Padding and Borders Within the Total Width and Height of All Elements on the Page.

In [ ]:
<style>
* {
    box-sizing: border-box
}

body {

    background-color: #eee;
    font-family: Arial, Helvetica, sans-serif;
}

.page-head,
.page-description {

    text-align: center;
}

.page-head {

    font-size: 40px;
    margin: 20px 0 0;
}

.page-description { 

    font-size: 22px;
    margin: 5px 0 40px;
}


Now the Page Should Look Like This: 

![first_css_edits](https://i.imgur.com/CiYB2Sc.png)

⟶ Now Let's Go to the skills.html File To Create the `Skill-Box` Class; the Class Which Will Deal with the Main Div of the Skill and It's Progress

In [ ]:
<style>
.skill-box { 

    background-color: #fff;
    padding: 20px;
    margin: 20px auto;
    border: 1px solid #ccc;
    width: 450px;
}

This Should Make the Page Like This: 

![skill-box](https://i.imgur.com/bUgVwLX.png)

Now Let's Remove The `|` And Put the Skill in a Div and the Progress in a Separate Div

↪ in the skills.html File: 

In [ ]:
{% extends 'base.html' %}
{% block body %} 

<h1 class="page-head"> {{ page_head }} </h1>

<p class="page-description"> {{ description }} </p>

{% for skill in skills %}

<div class="skill-box">

    <div class="skill-name"> {{ skill[0] }} </div>
    <div class="skill-progress"> {{ skill[1] }} </div>

</div>

{% endfor %}

{% endblock %}

This Should Make the Page Like This: 

![Two Divs](https://i.imgur.com/EfARsTD.png)

↪ Now Back to skills.css

In [ ]:
<style>
.skill-box .skill-name {

    text-align: center;
    margin-bottom: 15px;
    font-size: 20px;
    font-weight: bold;
}


.skill-box .skill-progress {

    background-color: #f7f7f7;
    padding: 10px;
    position: relative;
}

↪ Now Back to skills.html File to Make the the Skill Progress in a `Span`

In [ ]:
{% extends 'base.html' %}
{% block body %} 

<h1 class="page-head"> {{ page_head }} </h1>

<p class="page-description"> {{ description }} </p>

{% for skill in skills %}

<div class="skill-box">

    <div class="skill-name"> {{ skill[0] }} </div>
    <div class="skill-progress">
        <span>  </span>
    </div>

</div>

{% endfor %}

{% endblock %}

↪ Now Let's Customize It in Css: 

In [ ]:
<style>
.skill-box .skill-progress span { 

    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background-color: green;
}

This Should Fill the Progress with Green Like This: 

![Filled Bars](https://i.imgur.com/bJzzGGT.png)

We Will Make the Width Value Dynamic so that if the Progress Is 70 the Width of the Progress Bar Will Also Be 70. 

↪ Set the Width to `0` for Now

↪ Now in the `skills.html` File Let's Edit the Span

In [ ]:
{% extends 'base.html' %}
{% block body %} 

<h1 class="page-head"> {{ page_head }} </h1>

<p class="page-description"> {{ description }} </p>

{% for skill in skills %}

<div class="skill-box">

    <div class="skill-name"> {{ skill[0] }} </div>
    <div class="skill-progress">
        <span style="width: {{ skill[1] }}%"></span>
    </div>

</div>

{% endfor %}

{% endblock %}

This Will Make the Bars Dynamic to the Values in the Python File. 

Now Let's Add One Item to the List in `my_skills` in the Python File and See the Result in the Browser, You Should See Something Like This: 

![Css Final](https://i.imgur.com/Q9JI6NV.png)

:: `Note` :: You Will Find a Red Flag Error on the Span Line in vs-Code because You We're Wrighting Code with Template Engine and vs Code Can't Understand It, to Turn It Off Go to vs-Code Settings and Search for `HTML > Validate: Style` and Turn It Off. 

Don't Worry Thats the Right Thing to Do Cuz You Will Be Writing a Lot of Render Templates and vs Code Wont' Understand It

`Adding Javascript Files`

❖ Now We Need to Add Jquery and the main.js File

`jQuery` is a fast, small, and feature-rich JavaScript library designed to simplify the client-side scripting of HTML. 

It essentially makes things like HTML document traversal and manipulation, event handling, animation, and Ajax much easier with an easy-to-use API that works across many different browsers. 

Here's a breakdown of its key characteristics:

`↪ Purpose`:

❖ To simplify JavaScript usage on websites, allowing developers to write less code and achieve more.

❖ To abstract away complex JavaScript patterns into concise and readable functions.

❖ To provide consistency across browsers by standardizing how common tasks are done.
 
`↪ Features`:

❖ DOM manipulation: Easily select, add, remove, and modify HTML elements on a page.

❖ Event handling: Efficiently manage user interactions like clicks, scrolls, and key presses.

❖ Animation: Create smooth and dynamic animated effects with minimal effort.

❖ Ajax: Make asynchronous calls to the server without refreshing the page.

❖ Utilities: Includes various helper functions for tasks like working with forms, cookies, and arrays.

`↪ Benefits`:

❖ Increased developer productivity: Writing less code saves time and reduces errors.

❖ Improved code readability and maintainability: Clear and concise APIs make code easier to understand and update.

❖ Cross-browser compatibility: Works consistently across different browsers due to its abstraction layer.

❖ Large community and ecosystem: Abundant resources, plugins, and tutorials available.

`↪ Popularity`:

Despite the emergence of newer JavaScript frameworks, jQuery remains one of the most popular web development libraries, with over 70% of the top 10 million websites using it.

While learning JavaScript from scratch is valuable, understanding jQuery can be beneficial for web development because it simplifies common tasks and allows you to focus on the logic and functionality of your web application.

You Can Install It Using This Command: 

In [ ]:
npm install jquery

Now You Need to Download the Jquery File From This Link: 

> https://releases.jquery.com

Download the Minified Version

Create a New Js File `main.js` in the static > js > main.js And Also Put the Jquery File with It in the Same Folder

↪ Go to base.html File

In [ ]:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ pagetitle }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename= 'css/main.css') }}"/>
    
    {% if custom_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/' + custom_css + '.css') }}"/>
    {% endif %}


</head>
<body>
    {% block body %} 
    {% endblock %}

    <!-- Adding the Javascript -->
    <script src="{{ url_for('static', filename= 'js/jquery-3.4.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename= 'js/main.js') }}"></script>
    

</body>
</html>

:: `VIP Note` :: The Order You Put the Scripts Is Very Important You Must Put the `Jquery` File First Before The `main.js` File Otherwise the Animation Won't Work

↪ Now Go to `skills.html` File To Create the Animation of the Progress

In [ ]:
{% extends 'base.html' %}
{% block body %} 

<h1 class="page-head"> {{ page_head }} </h1>

<p class="page-description"> {{ description }} </p>

{% for skill in skills %}

<div class="skill-box">

    <div class="skill-name"> {{ skill[0] }} </div>
    <div class="skill-progress">
        
        <!-- Adding The jQuery: data-width And Set It to Skill Progress -->
        <span data-width = " {{ skill[1] }}%"></span>
    </div>

</div>

{% endfor %}

{% endblock %}

↪ Now Go to `main.js` File To Create the Function

In [ ]:
$(function () {

    $(".skill-progress span").each(function () {

        $(this).animate({

            'width' : $(this).data("width")

        }, 1000); 

    });
})

Let's Walk Through What This jQuery Code Is Doing:

`$(function () {` This is shorthand for $(document).ready(function() { ... }). It makes sure all the jQuery code inside it only runs once the DOM is fully loaded and ready.

`DOM` stands for "Document Object Model". It is a programming interface for web documents.

The DOM represents the document as nodes and objects so that programming languages can interact with the page. It essentially takes an HTML document and converts it into an object-oriented representation.

Some key things to know about the DOM:

❖ It's a structured representation of an HTML document that connects all the elements as objects

❖ JavaScript can use the DOM to access, traverse, manipulate, and add/remove elements on a page

❖ The DOM is automatically created by the browser when a webpage loads

❖ It has methods like getElementById, querySelector, addEventListener, etc to interact with elements

❖ Nodes on the DOM include the document itself, elements, text content, attributes, and more

❖ Modifying the DOM updates what the user sees on the page


So in summary, the DOM allows JavaScript to "see" an HTML document as a structured network of nodes it can manipulate. It provides an interface to traverse and alter document content and structure.

When `jQuery` code refers to the DOM ready event, like $(document).ready(), it means "run this JavaScript after the DOM has been constructed". This ensures the script can properly find/use all elements on the page.

In [ ]:
$(".skill-progress span").each(function () {

This finds all the `<span>` elements inside elements with a class of "skill-progress". For each one, it will execute the function to animate the width.

In [ ]:
$(this).animate({
    'width' : $(this).data("width") 
  }, 1000);

For Each Span, It Calls jQuery's `animate()` Method to Change the Width CSS Property Over `1000 milliseconds` (1 second).

The New Width It Animates to Is Retrieved From that Element's Data-Width Attribute Using .data("width").

So that Span Must Have Something Like:

In [ ]:
<span data-width="50">...</span>

Which Means It Would Animate the Width From 0px to 50% over 1 Second.

In [ ]:
});

})

Just Closes the Each Loop and Document Ready Handler.

__So in Summary__:

❖ Wait for document ready

❖ Find all spans in skill-progress elements

❖ Animate width of each over 1 sec based on data attribute


##### **NumPy and Arrays**

❖ NumPy Is A Python Third-Party Module To Deal With Arrays & Matrices

❖ NumPy Stand For Numerical Python

❖ NumPy Is Open Source

❖ NumPy Support Dealing With Large Multidimensional Arrays & Matrices

❖ NumPy Has Many Mathematical Functions To Deal With This Elements

# ------------------------------------------------------------

:: `Why We Use NumPy Array` ::

❖ Consume Less Memory

❖ Very Fast Compared To Python List

❖ Easy To Use

❖ Support Element Wise Operation

❖ Elements Are Stored Contiguous

# -------------------------------------------

**Python Lists**

↪ `Homogeneous` => Can Contains The Same Type of Objects

↪ `Heterogeneous` => Can Contains Different Types of Objects.

# --------------------------------------------------------------

❖ The Items in The Array Have to Be Of The Same Type

❖ You Can Be Sure Whats The Storage Size Needed for The Array

❖ NumPy Arrays Are Indexed From 0

# --------------------------------------------------------------

> NumPy On Github => https://github.com/numpy/numpy


In [1]:
import numpy as np

print(np.__version__)

1.26.3


:: `NumPy – Create Arrays` ::

In [3]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_list)
print(my_array)
print(type(my_list))
print(type(my_array))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


`ndarray` stands for N-dimensional array or multidimensional. This means ndarrays can represent data with any number of dimensions. For example - 1D, 2D, 3D arrays etc.

In [4]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_list[0])
print(my_array[0])

1
1


In [6]:
import numpy as np
a = np.array(10)
b = np.array([10, 20])
c = np.array( [ [1, 2], [3, 4] ] )
d = np.array( [ [ [5, 6], [7, 9] ], [ [1, 3], [4, 8] ] ] )

print(d[1][1][-1])
print(d[1, 1, 1])
print(d[1, 1, -1])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

8
8
8
0
1
2
3


`ndim` Stands for Number Of Dimensions

In [7]:
import numpy as np
my_custom_array = np.array([1, 2, 3], ndmin=3)
print(my_custom_array)
print(my_custom_array.ndim)

print(my_custom_array[0, 0, 0])

[[[1 2 3]]]
3
1


`ndmin` Stands for Minimum Number of Arrays

:: `Compare Data Location And Type` ::

In [8]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array([1, 2, 3, 4, 5])

print(my_list[0])
print(my_list[1])

print(my_array[0])
print(my_array[1])

1
2
1
2


In [9]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array([1, 2, 3, 4, 5])

print(id(my_list[0]))
print(id(my_list[1]))

print(id(my_array[0]))
print(id(my_array[1]))

4387572592
4387572624
4583161616
4583161616


In [10]:
import numpy as np

my_list_of_data = [1, 2, "A", "B", True, 10.50]
my_array_of_data = np.array([1, 2, "A", "B", True, 10.50])

print(my_list_of_data)
print(my_array_of_data)

[1, 2, 'A', 'B', True, 10.5]
['1' '2' 'A' 'B' 'True' '10.5']


In [11]:
import numpy as np

my_list_of_data = [1, 2, "A", "B", True, 10.50]
my_array_of_data = np.array([1, 2, "A", "B", True, 10.50])

print(my_list_of_data[0])
print(my_array_of_data[0])

print(type(my_list_of_data[0]))
print(type(my_array_of_data[0]))

1
1
<class 'int'>
<class 'numpy.str_'>


In [12]:
import numpy as np

my_list_of_data_two = [1, 2, "A", "B", True, 10.50]
my_array_of_data_two = np.array([1, 2, "A"])

print(my_list_of_data_two)
print(my_array_of_data_two)

[1, 2, 'A', 'B', True, 10.5]
['1' '2' 'A']


In [13]:
import numpy as np

my_list_of_data_two = [1, 2, "A", "B", True, 10.50]
my_array_of_data_two = np.array([1, 2, "A"])

print(my_list_of_data_two[0])
print(my_array_of_data_two[0])

print(type(my_list_of_data_two[0]))
print(type(my_array_of_data_two[0]))

1
1
<class 'int'>
<class 'numpy.str_'>


:: `Array Slicing` ::

In [14]:
import numpy as np

a = np.array(["A", "B", "C", "D", "E", "F"])

print(a.ndim)
print(a[1])
print(a[1:4])
print(a[:4])
print(a[2:])

1
B
['B' 'C' 'D']
['A' 'B' 'C' 'D']
['C' 'D' 'E' 'F']


In [17]:
b = np.array([["A", "B", "X"], ["C", "D", "Y"], ["E", "F", "Z"], ["M", "N", "O"]])

print(b.ndim)
print(b[1])
print("#" * 20)
print(b[2:, :2])
print(b[2:, :2:2])

2
['C' 'D' 'Y']
####################
[['E' 'F']
 ['M' 'N']]
[['E']
 ['M']]


:: `NumPy – Data Types And Control Array` ::

> https://numpy.org/devdocs/user/basics.types.html

> https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html#specifying-and-constructing-data-types


❖ '`?`' boolean

❖ '`b`' (signed) byte

❖ '`B`' unsigned byte

❖ '`i`' (signed) integer

❖ '`u`' unsigned integer

❖ '`f`' floating-point

❖ '`c`' complex-floating point

❖ '`m`' timedelta

❖ '`M`' datetime

❖ '`O`' (Python) objects

❖ '`S`', 'a' zero-terminated bytes (not recommended)

❖ '`U`' Unicode string

❖ '`V`' raw data (void)


In [18]:
import numpy as np

my_array1 = np.array([1, 2, 3])
my_array2 = np.array([1.5, 20.15, 3.601])
my_array3 = np.array(["Osama_Elzero", "B", "Ahmed"])

print(my_array1.dtype)
print(my_array2.dtype)
print(my_array3.dtype)

int64
float64
<U12


In [19]:
import numpy as np

# Create Array With Specific Data Type

my_array4 = np.array([1, 2, 3], dtype=float) # float Or 'float' Or 'f'
my_array5 = np.array([1.5, 20.15, 3.601], dtype=int) # int Or 'int' Or 'i'
# my_array6 = np.array(["Osama_Elzero", "B", "Ahmed"], dtype=int) # Value Error

print(my_array4.dtype)
print(my_array5.dtype)
# print(my_array6.dtype)


float64
int64


In [20]:
import numpy as np
my_array7 = np.array([0, 1, 2, 3, 0, 4])
print(my_array7.dtype)
print(my_array7)

int64
[0 1 2 3 0 4]


In [21]:
import numpy as np

my_array7 = my_array7.astype('float')
print(my_array7.dtype)
print(my_array7)

float64
[0. 1. 2. 3. 0. 4.]


In [ ]:
import numpy as np
my_array7 = my_array7.astype('bool')
print(my_array7.dtype)
print(my_array7)

In [22]:
# Test Capacity

my_array8 = np.array([100, 200, 300, 400], dtype='f')
print(my_array8.dtype)
print(my_array8[0].itemsize) # 4 Bytes

my_array8 = my_array8.astype('float') # Change To Float64
print(my_array8.dtype)
print(my_array8[0].itemsize) # 8 Bytes

float32
4
float64
8


:: `Arithmetic And Useful Operations` ::

❖ Addition

❖ Subtraction

❖ Multiplication

❖ Dividation

# ----------------

❖ min

❖ max

❖ sum

❖ ravel => Returns Flattened Array 1 Dimension With Same Type


In [23]:
import numpy as np

# Arithmetic Operations

my_array1 = np.array([10, 20, 30])
my_array2 = np.array([5, 2, 4])

print(my_array1 + my_array2) # result [15, 22, 34]
print(my_array1 - my_array2) # result [5, 18, 26]
print(my_array1 * my_array2) # result [50, 40, 120]
print(my_array1 / my_array2) # result [2, 10, 7.5]

[15 22 34]
[ 5 18 26]
[ 50  40 120]
[ 2.  10.   7.5]


In [ ]:
import numpy as np

my_array3 = np.array([[1, 4], [5, 9]])
my_array4 = np.array([[2, 7], [10, 5]])

print(my_array3 + my_array4) # result [ [3, 11], [15, 14] ]
print(my_array3 - my_array4) # result [ [-1, -3], [-5, 4] ]
print(my_array3 * my_array4) # result [ [2, 28], [50, 45] ]
print(my_array3 / my_array4) # result [ [0.5, 0.57142857], [0.5, 1.8] ]

In [25]:
import numpy as np

my_array5 = np.array([10, 20, 30])
print(my_array5.min())
print(my_array5.max())
print(my_array5.sum())

10
30
60


In [26]:
import numpy as np

my_array6 = np.array([[6, 4], [3, 9]])
print(my_array6.min())
print(my_array6.max())
print(my_array6.sum())

3
9
22


In [27]:
import numpy as np

my_array7 = np.array([[6, 4], [3, 9]])
print(my_array7.ravel())

[6 4 3 9]


In [ ]:
import numpy as np

my_array8 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(my_array8.ndim)
print(my_array8.ravel())
x = my_array8.ravel()
print(x.ndim)

:: `NumPy – Array Shape And ReShape` ::

Shape Returns A Tuple Contains The Number Of Elements in Each Dimension

In [28]:
import numpy as np

my_array1 = np.array([1, 2, 3, 4])
print(my_array1.ndim)
print(my_array1.shape)

1
(4,)


In [29]:
import numpy as np

my_array2 = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
print(my_array2.ndim)
print(my_array2.shape)

2
(3, 4)


In [30]:
import numpy as np

my_array3 = np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]])
print(my_array3.ndim)
print(my_array3.shape)

3
(2, 2, 3)


In [31]:
import numpy as np

my_array4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(my_array4.ndim)
print(my_array4.shape)

1
(12,)


In [32]:
import numpy as np
my_array4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_array4 = my_array4.reshape(3, 4)
print(reshaped_array4.ndim)
print(reshaped_array4.shape)
print(reshaped_array4)

2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
import numpy as np

my_array5 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
print(my_array5.ndim)
print(my_array5.shape)

2
(2, 10)


In [34]:
import numpy as np

my_array5 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
reshaped_array5 = my_array5.reshape(2, 5, 2)
print(reshaped_array5.ndim)
print(reshaped_array5.shape)
print(reshaped_array5)

3
(2, 5, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]]
